### ISSUE TITLE
Two huge issues

### ISSUE THREAD

**Issue by samlobel** [bennylope/django-simple-auth#2]
First, this seems to store passwords in plain text. Am I seeing that right? If so, that's not a good idea.

Second, this seems to match against any password, not just this User's password. So if my password is p1, and yours is p2, and I submit my username with your password, I'm authenticated. That doesn't seem like a good idea.

**Comment by bennylope** [comment]
Thanks for checking this app out! Did you read the repo description?

> Configurable, password-only authorization for *slightly* sensitive material. Not a Django authentication replacement, it's like HTTP basic auth but easier for users (and less secure!)

I replaced "authentication" with "authorization" in that description but otherwise it's the same as before. **This is not a user management system**, it's designed to allow _public_ access to URLs using shared passwords; these are hall passes, not identification cards. It sounds like you're looking for a replacement for `contrib.auth` but this is not it.

I've updated the README to clarify this, hopefully that helps!
